### ISSUE TITLE
[JOSS REVIEW] Suggestions for Software Paper

### ISSUE THREAD

**Issue by xin-huang** [AngryMaciek/angry-moran-simulator#6]
This is a part of the JOSS review (https://github.com/openjournals/joss-reviews/issues/2643)

1. As the checklist suggests, a Summary section is required in the paper. 
2. Although the authors discussed some other simulators (DEAP and Axelrod) in the statement of need, I suggest the authors separate these discussion into a State of the field section, as the checklist suggests, or merge them into the Introduction section.

**Comment by rozmanowna** [comment]
Thank you for the comments @xin-huang! 

I added Summary and State of the field sections as you suggested.

Here is the link to new pdf paper: https://github.com/openjournals/joss-reviews/issues/2643#issuecomment-689807532

**Comment by xin-huang** [comment]
Hi @rozmanowna, thanks for revising the paper.
But I still feel confused about this sentence

`Notably, another powerful Python package - Axelrod - allows to model evolution of cooperation in various strategies, but unlike Moran Pycess is limited to Prisoners’Dilemma only (The Axelrod project developers, 2016)`

It looks like the exact meaning should be 
`Notably, another powerful Python package - Axelrod - is limited to Prisoners' Dilemma, while Moran Pycess allows to model evolution of cooperation in various strategies`

Another concern is "population's evolution" in the Summary section.  I feel it is redundant to say population's evolution. I think simply using evolution is OK.

**Comment by rozmanowna** [comment]
Thank you @xin-huang, I have addressed your additional suggestions.

Here is the link to new pdf paper: https://github.com/openjournals/joss-reviews/issues/2643#issuecomment-690122031

**Comment by xin-huang** [comment]
Thanks @rozmanowna, I have no further concerns.
