### ISSUE TITLE
[JOSS Review] Conda installation "Conflicts found"

### ISSUE THREAD

**Issue by tkchafin** [AngryMaciek/angry-moran-simulator#7]
This is a part of the JOSS review (openjournals/joss-reviews#2643)

Environment creation as suggested in the documentation yields a bunch of conflicts found by conda. I was able to amend this by relaxing the version constraints in the .yml file like so: 

---

  name: moranpycess
    
  channels:
    - bioconda
    - conda-forge
    
  dependencies:
    - matplotlib=3.3
    - numpy=1.19
    - pandas
    - pip=20.1
    - python=3.7

...

Also, as suggested by @xin-huang, I would request that you add any additional dependencies needed for plotting, such as seaborn.

**Comment by AngryMaciek** [comment]
Dear @tkchafin ,
I have added a build on Travis macOS machine to the CI in https://github.com/AngryMaciek/angry-moran-simulator/commit/cc8235e1f27071301b807f1025f1aa6d0f6c2c73, please take a look at the attached build logs:
https://travis-ci.org/github/AngryMaciek/angry-moran-simulator/builds/725193448
It did not yield any conda conflicts. I have also built the environment on my personal mac, with no conflicts either. Are you using an older conda version, perhaps?

**Comment by AngryMaciek** [comment]
Dear @tkchafin 
Are there any other modifications you would like me to implement?

**Comment by majensen** [comment]
@tkchafin can you comment here or back at https://github.com/openjournals/joss-reviews/issues/2643 ? Thanks very much -- @majensen

**Comment by tkchafin** [comment]
Hi sorry about the delay- in the middle of a move. @AngryMaciek either explicitly list dependencies in README/ docs or relax the version constraints in the yaml file. Ideally both, or give some justification why such specific version constraints are needed.

**Comment by AngryMaciek** [comment]
OK, I have elaborted a little the `installation` section in the README by providing links to the *YAML* files which state the versions of the dependancies.

To care about *reproducible research* you generally want to be as specific as possible. You cannot guarantee that your code will work with many possible versions - you can guarantee just the one you are testing it with. So your code may be OK with `dependency1=0.1.0` but break on `dependency1=0.1.4`, who knows? Theoretically... This should not happen with patch versions updates but we cannot count that all the other developers stick to proper semantic versioning.
