### ISSUE TITLE
[JOSS Review] Insufficient documentation for plotting functions.

### ISSUE THREAD

**Issue by tkchafin** [AngryMaciek/angry-moran-simulator#8]
This is a part of the JOSS review (openjournals/joss-reviews#2643)

Documentation in 'documentation.md' is not sufficient for the MoranProcess plotting methods. (PlotSize, PlotAvgBirthPayoff, PlotAvgDeathPayoff, PlotBirthFitness, PlotDeathFitness, PlotEntropy).Please amend by providing explicit examples.

**Comment by AngryMaciek** [comment]
Dear @tkchafin,
Thanks a lot for the notice, indeed there were mistakes in the description of these functions.
In 3be60f5 I have introduced proper information about their execution.
Please take a look at the updated documentation.

**Comment by tkchafin** [comment]
Looks good 👍
