### ISSUE TITLE
[JOSS Review] Writing quality suggestions for software paper

### ISSUE THREAD

**Issue by tkchafin** [AngryMaciek/angry-moran-simulator#9]
This is a part of the JOSS review (openjournals/joss-reviews#2643)

Some very minor suggestions to improve clarity of the software paper: 

- ESS versus EES is not consistent. Please fix to the correct abbreviation (=ESS?)
- Intro L1: "Population is created by" would be more clearly written as "A population consists of individuals" or similar
- Intro L2-4: "Population characteristics, including: ..." would be more clearly written as something like "Population characteristics (e.g., reproduction, .... etc) change over time as a result of evolutionary mechanisms" 
- Intro L4: "*A* complicated network of..." 
- Intro L12: EES or ESS?
- Intro L13: should it be "evolutionarily" stable? 
- Statement of need L1: Perhaps mention the name of the package in the first sentence?
- Statement of need L2: "Contrary to cellular automata"? Perhaps revise for clarity
- Statement of need L13: "An open source license"
- Example (A) L2: Define "player"

**Comment by rozmanowna** [comment]
@tkchafin thank you for the comments!

I hope I have addressed all of your suggestions.

I wonder about the concept of "player": if we consider abstract models of conflict situations like Prisoners' Dilemma - in this context, the concept of a player seems to be as basic as the concept of the "game" itself and it is hard to find a clear definition. It is simply a participant in the game and in our eyes it does not require further specification. To make it clearer in the text as such I have added "game" in Example (A) L1 in the text. I hope you find this sufficient?

Here is the link to new pdf paper: https://github.com/openjournals/joss-reviews/issues/2643#issuecomment-689807532
